name: Gradle Package

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: 1. CheckOut Source
      uses: actions/checkout@v3

    - name: 2. Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: 3. Change Execution mode
      run: chmod 755 gradlew

    - name: 4. Install Mysql
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        mysql version: '8.0'
        mysql database: 'istory'
        mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        # 이 아래 두 개는 없어도 됨
        # 에러나면 mysql user가 아니라 mysql username으로 수정....
        mysql user: ${{ secrets.MYSQL_USER }}
        mysql password: ${{ secrets.MYSQL_PASSWORD }}

    - name: 5. Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: 6. Docker Image build
      run: docker build ./xinfra/docker -t ${{ secrets.DOCKER_USERNAME }}/istory -f ./xinfra/docker/Dockerfile

    - name: 7. Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        logout: true

    # 주의! 이대로하면 latest, 버전 명시해야 함
    - name: 8. Docker push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/istory


#    - name: Publish to GitHub Packages
#      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#      with:
#        arguments: publish
#      env:
#        USERNAME: ${{ github.actor }}
#        TOKEN: ${{ secrets.GITHUB_TOKEN }}
